name: Factions
main: AndreasHGK\Factions\Factions
version: 0.0.1
api: 3.8.0
load: POSTWORLD
author: AndreasHGK
description: Factions for the HGK server
website: http://hgk.me/
depend:
- AutoCompleteAPI

permissions:
 #Root permission node
 skeleton:
  #Default state of this permission. `op` means that only server operators will have this permission by default.
  default: true
  #Description of what the permission does or doesn't allow.
  description: "Example root permission node"
  #Child permission nodes. If the parent permission node is true, the children will have the values set here. If false, all child permissions will be inverted.
  children:
   skeleton.command:
    default: true
    description: "Allows the use of /examplecommand"